# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://doas3140.github.io/facelib/"

git_url = "https://github.com/doas3140/facelib/tree/master/"

def custom_doc_links(name): return None
