# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/06_face_cropped_training.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastai import *
from fastai.vision import *
import pandas as pd
import numpy as np
import cv2
from tqdm.notebook import tqdm
import xml.etree.ElementTree as ET
from torch.autograd import Variable
from fastai.callbacks import LossMetrics
from pathlib import Path

# Cell
import matplotlib.pyplot as plt